// Generated by CoffeeScript 2.5.1
// import _ from 'https://cdn.skypack.dev/lodash'
// import {log,range,r4r} from '../js/utils.js'
var a, click;

import {
  r4r,
  log,
  button,
  div,
  textarea
} from '../js/utils.js';

a = null;

click = () => {
  a.hidden = false;
  a.value = "1 b3";
  a.select();
  document.execCommand('copy');
  a.hidden = true;
  return window.location.href = 'https://lichess.org/paste';
};

r4r(() => {
  return div({}, a = textarea({
    hidden: true
  }), button({
    onclick: click
  }, 'analyze'));
});

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWVcXHNrZXRjaC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUM4Qzs7QUFBQSxJQUFBLENBQUEsRUFBQTs7QUFDOUMsT0FBQTtFQUFRLEdBQVI7RUFBWSxHQUFaO0VBQWdCLE1BQWhCO0VBQXVCLEdBQXZCO0VBQTJCLFFBQTNCO0NBQUEsTUFBQTs7QUFFQSxDQUFBLEdBQUk7O0FBRUosS0FBQSxHQUFRLENBQUEsQ0FBQSxHQUFBO0VBQ1AsQ0FBQyxDQUFDLE1BQUYsR0FBVztFQUNYLENBQUMsQ0FBQyxLQUFGLEdBQVU7RUFDVixDQUFDLENBQUMsTUFBRixDQUFBO0VBQ0EsUUFBUSxDQUFDLFdBQVQsQ0FBcUIsTUFBckI7RUFDQSxDQUFDLENBQUMsTUFBRixHQUFXO1NBQ1gsTUFBTSxDQUFDLFFBQVEsQ0FBQyxJQUFoQixHQUF1QjtBQU5oQjs7QUFRUixHQUFBLENBQUksQ0FBQSxDQUFBLEdBQUE7U0FBRyxHQUFBLENBQUksQ0FBQSxDQUFKLEVBQ04sQ0FBQSxHQUFJLFFBQUEsQ0FBUztJQUFDLE1BQUEsRUFBTztFQUFSLENBQVQsQ0FERSxFQUVOLE1BQUEsQ0FBTztJQUFDLE9BQUEsRUFBUztFQUFWLENBQVAsRUFDQyxTQURELENBRk07QUFBSCxDQUFKIiwic291cmNlc0NvbnRlbnQiOlsiIyBpbXBvcnQgXyBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi9sb2Rhc2gnXHJcbiMgaW1wb3J0IHtsb2cscmFuZ2UscjRyfSBmcm9tICcuLi9qcy91dGlscy5qcydcclxuaW1wb3J0IHtyNHIsbG9nLGJ1dHRvbixkaXYsdGV4dGFyZWF9IGZyb20gJy4uL2pzL3V0aWxzLmpzJ1xyXG5cclxuYSA9IG51bGxcclxuXHJcbmNsaWNrID0gPT5cclxuXHRhLmhpZGRlbiA9IGZhbHNlXHJcblx0YS52YWx1ZSA9IFwiMSBiM1wiXHJcblx0YS5zZWxlY3QoKVxyXG5cdGRvY3VtZW50LmV4ZWNDb21tYW5kICdjb3B5J1xyXG5cdGEuaGlkZGVuID0gdHJ1ZVxyXG5cdHdpbmRvdy5sb2NhdGlvbi5ocmVmID0gJ2h0dHBzOi8vbGljaGVzcy5vcmcvcGFzdGUnXHJcblxyXG5yNHIgPT4gZGl2IHt9LFxyXG5cdGEgPSB0ZXh0YXJlYSB7aGlkZGVuOnRydWV9XHJcblx0YnV0dG9uIHtvbmNsaWNrOiBjbGlja30sXHJcblx0XHQnYW5hbHl6ZSdcclxuIl19
//# sourceURL=c:\github\2023-011-solidjs-coffee\coffee\sketch.coffee