// Generated by CoffeeScript 2.5.1
// import _ from 'https://cdn.skypack.dev/lodash'
// import {log,range,r4r} from '../js/utils.js'
var a, click;

import {
  r4r,
  log,
  button,
  div,
  textarea
} from '../js/utils.js';

a = null;

click = () => {
  a.select();
  document.execCommand('copy');
  return window.location.href = 'https://lichess.org/paste';
};

r4r(() => {
  return div({}, a = textarea({}, '1 e4 c5'), button({
    onclick: click
  }, 'analyze'));
});

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWVcXHNrZXRjaC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUM4Qzs7QUFBQSxJQUFBLENBQUEsRUFBQTs7QUFDOUMsT0FBQTtFQUFRLEdBQVI7RUFBWSxHQUFaO0VBQWdCLE1BQWhCO0VBQXVCLEdBQXZCO0VBQTJCLFFBQTNCO0NBQUEsTUFBQTs7QUFFQSxDQUFBLEdBQUk7O0FBRUosS0FBQSxHQUFRLENBQUEsQ0FBQSxHQUFBO0VBQ1AsQ0FBQyxDQUFDLE1BQUYsQ0FBQTtFQUNBLFFBQVEsQ0FBQyxXQUFULENBQXFCLE1BQXJCO1NBQ0EsTUFBTSxDQUFDLFFBQVEsQ0FBQyxJQUFoQixHQUF1QjtBQUhoQjs7QUFLUixHQUFBLENBQUksQ0FBQSxDQUFBLEdBQUE7U0FBRyxHQUFBLENBQUksQ0FBQSxDQUFKLEVBQ04sQ0FBQSxHQUFJLFFBQUEsQ0FBUyxDQUFBLENBQVQsRUFDSCxTQURHLENBREUsRUFHTixNQUFBLENBQU87SUFBQyxPQUFBLEVBQVM7RUFBVixDQUFQLEVBQ0MsU0FERCxDQUhNO0FBQUgsQ0FBSiIsInNvdXJjZXNDb250ZW50IjpbIiMgaW1wb3J0IF8gZnJvbSAnaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvbG9kYXNoJ1xyXG4jIGltcG9ydCB7bG9nLHJhbmdlLHI0cn0gZnJvbSAnLi4vanMvdXRpbHMuanMnXHJcbmltcG9ydCB7cjRyLGxvZyxidXR0b24sZGl2LHRleHRhcmVhfSBmcm9tICcuLi9qcy91dGlscy5qcydcclxuXHJcbmEgPSBudWxsXHJcblxyXG5jbGljayA9ID0+XHJcblx0YS5zZWxlY3QoKVxyXG5cdGRvY3VtZW50LmV4ZWNDb21tYW5kICdjb3B5J1xyXG5cdHdpbmRvdy5sb2NhdGlvbi5ocmVmID0gJ2h0dHBzOi8vbGljaGVzcy5vcmcvcGFzdGUnXHJcblxyXG5yNHIgPT4gZGl2IHt9LFxyXG5cdGEgPSB0ZXh0YXJlYSB7fSxcclxuXHRcdCcxIGU0IGM1J1xyXG5cdGJ1dHRvbiB7b25jbGljazogY2xpY2t9LFxyXG5cdFx0J2FuYWx5emUnXHJcbiJdfQ==
//# sourceURL=c:\github\2023-011-solidjs-coffee\coffee\sketch.coffee